name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: Dickens-Shaw/documents@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Dickens-Shaw/documents
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && build
        BUILD_DIR: docs/.vuepress/dist