name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: vuepress-deploy
      uses: Dickens-Shaw/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.METRICS_TOKEN }}
        TARGET_REPO: Dickens-Shaw/documents
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: git config --global --add safe.directory "*" && yarn && yarn build
        BUILD_DIR: dist 