name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: 'master'

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies && Build assets
      run: |
        npm install --frozen-lockfile
        npm run build

    - name: Deploy to GitHub Pages
      uses: Dickens-Shaw/documents@master
      with:
        target_branch: gh-pages
        build_dir: docs/.vuepress/dist
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Dickens-Shaw/documents